//go:build gates

package gates

import (
	"errors"
	"os"
	"path/filepath"
	"sort"
	"testing"

	opentile "github.com/wsilabs/opentile-go"
	_ "github.com/wsilabs/opentile-go/formats/all"
	"github.com/wsilabs/opentile-go/internal/tiff"
)

// TestT2StrippedSVSReleasesFromSVSDetector verifies that the
// stripped-SVS fixtures (generated by sample_files/generic-tiff/regen.py)
// are no longer claimed by the SVS factory's detector. After regen.py
// mutates IFD 0's "Aperio" prefix to "Custom", the SVS detector's
// HasPrefix check should return false → the file falls through the
// dispatch loop. With no generic factory yet (T6+ work), the
// expected outcome is opentile.ErrUnsupportedFormat.
//
// This validates the spec §1 framing: "stripped-SVS = a real SVS
// minus the Aperio marker, falls through to the (future) generic
// factory."
func TestT2StrippedSVSReleasesFromSVSDetector(t *testing.T) {
	dir := os.Getenv("OPENTILE_TESTDIR")
	if dir == "" {
		t.Skip("OPENTILE_TESTDIR not set")
	}

	fixtures := []string{
		"CMU-1.stripped.tiff",
		"CMU-1-Small-Region.stripped.tiff",
	}

	for _, name := range fixtures {
		t.Run(name, func(t *testing.T) {
			path := filepath.Join(dir, "generic-tiff", name)
			if _, err := os.Stat(path); err != nil {
				t.Skipf("%s not present (run regen.py first)", path)
			}

			// Pre-T6: opening should error with ErrUnsupportedFormat
			// (SVS rejects on missing Aperio prefix; no other factory
			// claims it; generic factory doesn't exist yet).
			_, err := opentile.OpenFile(path)
			if err == nil {
				t.Fatal("expected error opening stripped SVS pre-T6, got nil")
			}
			if !errors.Is(err, opentile.ErrUnsupportedFormat) {
				t.Errorf("got %v, want ErrUnsupportedFormat", err)
			}
			t.Logf("✓ %s correctly rejected pre-T6: %v", name, err)
		})
	}
}

// TestT2StrippedSVSPyramidValidatorAcceptance probes the stripped
// CMU-1.stripped.tiff against the v0.10 pyramid validator rules.
// Records findings about what the future generic factory will
// accept + how the heuristic classifier (T9) needs to handle the
// associated IFDs.
func TestT2StrippedSVSPyramidValidatorAcceptance(t *testing.T) {
	dir := os.Getenv("OPENTILE_TESTDIR")
	if dir == "" {
		t.Skip("OPENTILE_TESTDIR not set")
	}

	for _, tc := range []struct {
		name           string
		expectAccept   bool
		expectPyramid  int
		expectStripped int
	}{
		// Multi-level: validator should accept (3 tiled pyramid IFDs).
		{"CMU-1.stripped.tiff", true, 3, 3},
		// Single-level: only 1 tiled IFD → validator rejects (<3).
		{"CMU-1-Small-Region.stripped.tiff", false, 1, 3},
	} {
		t.Run(tc.name, func(t *testing.T) {
			path := filepath.Join(dir, "generic-tiff", tc.name)
			if _, err := os.Stat(path); err != nil {
				t.Skipf("%s not present", path)
			}
			f, err := os.Open(path)
			if err != nil {
				t.Fatal(err)
			}
			defer f.Close()
			st, _ := f.Stat()
			tf, err := tiff.Open(f, st.Size())
			if err != nil {
				t.Fatalf("tiff.Open: %v", err)
			}

			pages := tf.Pages()
			t.Logf("%s: %d total IFDs", tc.name, len(pages))

			var tiled []candidate
			var stripped []candidate
			for i, p := range pages {
				tw, hasTW := p.TileWidth()
				th, _ := p.TileLength()
				iw, _ := p.ImageWidth()
				il, _ := p.ImageLength()
				comp, _ := p.Compression()
				photo, _ := p.Photometric()
				spp, _ := p.SamplesPerPixel()
				c := candidate{
					idx: i, w: int(iw), h: int(il), tw: int(tw), th: int(th),
					area:        int64(iw) * int64(il),
					compression: comp, photometric: photo, samplesPerPix: spp,
				}
				if hasTW && tw != 0 {
					tiled = append(tiled, c)
				} else {
					stripped = append(stripped, c)
				}
			}
			sort.Slice(tiled, func(i, j int) bool { return tiled[i].area > tiled[j].area })

			t.Logf("  tiled: %d", len(tiled))
			for _, c := range tiled {
				t.Logf("    IFD %d: %d×%d comp=%d photo=%d spp=%d  tile=%d×%d",
					c.idx, c.w, c.h, c.compression, c.photometric, c.samplesPerPix, c.tw, c.th)
			}
			t.Logf("  stripped (associated candidates): %d", len(stripped))
			for _, c := range stripped {
				aspect := float64(c.w) / float64(c.h)
				t.Logf("    IFD %d: %d×%d comp=%d aspect=%.2f",
					c.idx, c.w, c.h, c.compression, aspect)
			}

			if got := len(tiled); got != tc.expectPyramid {
				t.Errorf("tiled count = %d, want %d", got, tc.expectPyramid)
			}
			if got := len(stripped); got != tc.expectStripped {
				t.Errorf("stripped count = %d, want %d", got, tc.expectStripped)
			}

			meetsMinLevels := len(tiled) >= 3
			if meetsMinLevels != tc.expectAccept {
				t.Errorf("meets ≥3-level requirement = %v, want %v", meetsMinLevels, tc.expectAccept)
			}

			// For the multi-level case, verify scale ratios pass.
			if tc.expectAccept && len(tiled) >= 2 {
				for i := 0; i < len(tiled)-1; i++ {
					rW := float64(tiled[i].w) / float64(tiled[i+1].w)
					rH := float64(tiled[i].h) / float64(tiled[i+1].h)
					interAxis := absDiff(rW, rH) / rW
					t.Logf("    L%d→L%d ratio_W=%.4f ratio_H=%.4f inter-axis=%.4f%%",
						i, i+1, rW, rH, interAxis*100)
				}
			}
		})
	}
}

func absDiff(a, b float64) float64 {
	if a > b {
		return a - b
	}
	return b - a
}
