//go:build gates

package gates

import (
	"errors"
	"math"
	"os"
	"path/filepath"
	"sort"
	"testing"

	opentile "github.com/wsilabs/opentile-go"
	_ "github.com/wsilabs/opentile-go/formats/all"
	"github.com/wsilabs/opentile-go/internal/tiff"
)

// TestT3SyntheticFixtures probes the four synthetic fixtures
// generated by scripts/regen-generic-tiff.py and pins their
// expected behavior:
//
//   - synth-pyramid-jpeg.tiff       — validator ACCEPT
//   - synth-pyramid-with-label.tiff — validator ACCEPT (+ LZW
//     associated for classifier)
//   - synth-bad-pyramid.tiff        — validator REJECT (inter-axis)
//   - synth-stripped-only.tiff      — validator REJECT (0 tiled)
//
// Each subtest manually applies the validator algorithm from
// spec §4 and asserts the expected outcome. T4's production-code
// helper (internal/tiff.ClassifyPyramid) implements the same
// algorithm.
//
// Pre-T6, all four fixtures should fail to open via opentile.OpenFile
// with ErrUnsupportedFormat (no generic factory yet). Once T6 lands,
// the two ACCEPT fixtures will open via the generic factory and the
// two REJECT fixtures will continue to fail.
func TestT3SyntheticFixtures(t *testing.T) {
	dir := os.Getenv("OPENTILE_TESTDIR")
	if dir == "" {
		t.Skip("OPENTILE_TESTDIR not set")
	}

	for _, tc := range []struct {
		name           string
		expectAccept   bool
		expectTiled    int
		expectStripped int
		// rejectReason: short word identifying why the validator
		// should reject, for documentation in the test output.
		rejectReason string
	}{
		{"synth-pyramid-jpeg.tiff", true, 3, 0, ""},
		{"synth-pyramid-with-label.tiff", true, 3, 1, ""},
		{"synth-bad-pyramid.tiff", false, 3, 0, "inter-axis exceeds ±2%"},
		{"synth-stripped-only.tiff", false, 0, 2, "0 tiled IFDs (need ≥3)"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			path := filepath.Join(dir, "generic-tiff", tc.name)
			if _, err := os.Stat(path); err != nil {
				t.Skipf("%s not present (run regen-generic-tiff.py)", path)
			}

			// Pre-T6: all of these should fail OpenFile with
			// ErrUnsupportedFormat (no generic factory yet).
			_, err := opentile.OpenFile(path)
			if err == nil {
				t.Fatal("expected error opening synthetic pre-T6")
			}
			if !errors.Is(err, opentile.ErrUnsupportedFormat) {
				t.Errorf("got %v, want ErrUnsupportedFormat", err)
			}

			// Manually apply validator algorithm.
			f, err := os.Open(path)
			if err != nil {
				t.Fatal(err)
			}
			defer f.Close()
			st, _ := f.Stat()
			tf, err := tiff.Open(f, st.Size())
			if err != nil {
				t.Fatalf("tiff.Open: %v", err)
			}

			pages := tf.Pages()
			var tiled, stripped []candidate
			for i, p := range pages {
				tw, hasTW := p.TileWidth()
				th, _ := p.TileLength()
				iw, _ := p.ImageWidth()
				il, _ := p.ImageLength()
				comp, _ := p.Compression()
				photo, _ := p.Photometric()
				spp, _ := p.SamplesPerPixel()
				c := candidate{
					idx: i, w: int(iw), h: int(il), tw: int(tw), th: int(th),
					area:        int64(iw) * int64(il),
					compression: comp, photometric: photo, samplesPerPix: spp,
				}
				if hasTW && tw != 0 {
					tiled = append(tiled, c)
				} else {
					stripped = append(stripped, c)
				}
			}
			sort.Slice(tiled, func(i, j int) bool { return tiled[i].area > tiled[j].area })

			t.Logf("%s: %d total IFDs (tiled=%d stripped=%d)",
				tc.name, len(pages), len(tiled), len(stripped))

			if got := len(tiled); got != tc.expectTiled {
				t.Errorf("tiled count = %d, want %d", got, tc.expectTiled)
			}
			if got := len(stripped); got != tc.expectStripped {
				t.Errorf("stripped count = %d, want %d", got, tc.expectStripped)
			}

			// Validator decision.
			validatorAccepts := len(tiled) >= 3
			if validatorAccepts {
				// Inter-axis check at each transition.
				for i := 0; i < len(tiled)-1; i++ {
					rW := float64(tiled[i].w) / float64(tiled[i+1].w)
					rH := float64(tiled[i].h) / float64(tiled[i+1].h)
					interAxis := math.Abs(rW-rH) / rW
					t.Logf("  L%d→L%d ratio_W=%.4f ratio_H=%.4f inter-axis=%.4f%%",
						i, i+1, rW, rH, interAxis*100)
					if interAxis > 0.02 {
						validatorAccepts = false
						t.Logf("  → reject: inter-axis %.4f%% exceeds ±2%%", interAxis*100)
					}
				}
			}

			if validatorAccepts != tc.expectAccept {
				t.Errorf("validator accepts = %v, want %v (%s)",
					validatorAccepts, tc.expectAccept, tc.rejectReason)
			} else if !tc.expectAccept {
				t.Logf("✓ correctly REJECTS (%s)", tc.rejectReason)
			} else {
				t.Logf("✓ correctly ACCEPTS")
			}
		})
	}
}
